openapi: 3.0.1
info:
  title: ePA VAU related API
  description: VAU related REST API for the ePA Sim based on open API
  version: 1.0.0
  contact:
    name: gematik GmbH
    email: software-development@gematik.de
    url: 'https://www.gematik.de'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
tags:
  - name: VauProxy
    description: VAU Proxy related operations

paths:
  /epa/testdriver/api/v1/vau/destroy:
    post:
      tags:
        - VauProxy
      summary: Destroy VAU (the VAU identity of the client will be destroyed)
      description: 'This operation destroys the VAU-CID.'
      operationId: destroyVauCid
      parameters:
        - $ref: '#/components/parameters/insurantId'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DestroyVauCidResponseDTO'
components:
  parameters:
    insurantId:
      name: x-insurantid
      in: header
      description: Health Record Identifier.
      required: true
      schema:
        $ref: 'shared.yaml#/components/schemas/KvnrType'
  schemas:
    DestroyVauCidResponseDTO:
      description: 'Returns the status of the VAU-CID destruction'
      allOf:
        - $ref: 'shared.yaml#/components/schemas/ResponseDTO'
        - type: object
          required:
            - status
          properties:
            status:
              type: string
              description: 'Status of the VAU-CID destruction'
              example: 'SUCCESS'