openapi: 3.0.3
info:
  title: EPA MHD Service (DEV Endpoints)
  version: 1.0.1-b.1
  description: Developer endpoints for EPA MHD Service
paths:
  /epa/mhd/setup:
    get:
      summary: index test documents
      tags:
        - DevReference
      responses:
        '200':
          description: Indexing successful
          content:
            application/json:
              schema:
                type: string
        '500':
          $ref: 'mhd-client.yaml#/components/responses/Error500'
  /epa/mhd/cleanup:
    get:
      summary: remove test documents
      tags:
        - DevReference
      responses:
        '200':
          description: removal successful
          content:
            application/json:
              schema:
                type: string
        '500':
          $ref: 'mhd-client.yaml#/components/responses/Error500'