openapi: 3.0.3

info:
  title: VAU Client API
  description: API for VAU Client
  version: 1.0.0

servers:
  - url: http://epa4all

tags:
  - name: VAU

paths:
  /VAU-Status:
    get:
      tags:
        - VAU
      operationId: getVauStatus
      description: todo
      parameters:
        - $ref: '#/components/parameters/useragent'
      responses:
        "200":
          $ref: '#/components/responses/VauStatus'
  /destroy:
    post:
      tags:
        - VAU
      operationId: destroyVauCid
      description: Destroy VAU (the VAU identity of the client)
      responses:
        "200":
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DestroyVauCidResponse'
        "404":
          description: VAU identity Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DestroyVauCidResponse'


components:
  responses:
    VauStatus:
      description: VAU Status Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/VauStatus'

  parameters:
    useragent:
      name: x-useragent
      in: header
      description: user agent information
      required: true
      schema:
        $ref: '#/components/schemas/UserAgentType'

  schemas:
    UserAgentType:
      description: "Information about client software with: ClientId(20 characters) + / + VersionNumber (1 to 15 characters)."
      type: string
      pattern: '^[a-zA-Z0-9\-]{1,20}\/[a-zA-Z0-9\-\.]{1,15}$'
      example: CLIENTID1234567890AB/2.1.12-45
    VauStatus:
      description: VAU Status Response
      type: object
      properties:
        VAU-Type:
          type: string
        VAU-Version:
          type: string
        User-Authentication:
          type: string
        KeyID:
          type: string
        Connection-Start:
          type: string
      required:
        - VAU-Type
        - VAU-Version
        - User-Authentication
        - KeyID
        - Connection-Start
    DestroyVauCidResponse:
      type: object
      properties:
        statusMessage:
          type: string
          description: Status of the VAU-CID destruction
          example: 'VAU identity destroyed'